### ISSUE TITLE
can't build `borsh` without `std`

### ISSUE THREAD

**Issue by pmnoxx** [near/borsh-rs#59] opened 2021-12-20 07:26 UTC
Building, `borsh` with not `std` fails, due to lack of `alloc`

```shell
> cargo build --no-default-features

error: cannot find macro `vec` in this scope
   --> borsh/src/de/mod.rs:283:30
    |
283 |             let mut result = vec![T::deserialize(buf)?];
    |                              ^^^
    |
    = note: consider importing one of these items:
            alloc::vec
            crate::maybestd::vec

error: could not compile `borsh` due to previous error
```

**Comment by austinabell** [comment] 2021-12-21 17:28
https://github.com/near/borsh-rs/pull/47 added this change, probably an easy fix. Not sure why the CI isn't configured to run on branches

**Comment by tspiteri** [comment] 2022-02-04 18:09
I think this was fixed in #79; it seems #78 was a duplicate of this issue.

**Closed** 2022-02-07 06:23 UTC
