### ISSUE TITLE
Support for serde::{Serialize, Deserialize}

### ISSUE THREAD

**Issue by dsxmachina** [near/borsh-rs#184] opened 2023-07-28 09:36 UTC
Hello,

I was wondering if it would be possible to add support for the generic serde Serialize + Deserialize traits,
as the borsch versions of them seem to be kind of similar.

The borsch_init functionality is a cool feature, but some users may want to opt-out of it and use serde instead.

As a benefit, you could automatically serialize + deserialize types from a lot of other crates, that currently implement the serde adapter, instead of having to wait for them to also add borsch support.

More and more crates are adding their own Versions of serialize and deserialize to the table (same with bincode, they use 'encode' and 'decode' in Version 2 - but at least they are still compatible with serde).
From my standpoint this is not a good development, as it defeats the purpose of a generalized interface (like serde) if noone really uses it.

**Comment by frol** [comment] 2023-07-29 17:01
Well, avoiding serde was [a design decision](https://borsh.io/):

<img width="786" alt="image" src="https://github.com/near/borsh-rs/assets/304265/542109e0-4b6f-4372-a4ac-62d6e2054273">

Serde requires to use its abstraction layer that used to be (yet to be confirmed these days) a significant contributor to the compiled code size and performance degradation. Also, when considering serde adaptors, one should keep consistency in mind (a bijective mapping between objects and their binary representations; there should be no two binary representations that deserialize into the same object; this is extremely useful for applications that use binary representation to compute hash).

@dsxmachina If you want to give it a try, it would be interesting to see how far this experiment can go and whether the old beliefs are still applicable these days.

**Comment by dsxmachina** [comment] 2023-07-30 12:29
Yes, this was what I was aiming at. I know you opted out of serde for performance reasons (and to enable the fancy 'init' feature) - but for me it would be okay to sacrifice performance over compatibility (and I don't know if code / binary size is an issue outside of the microcontroller world).

The question was more a "is it possible in principle" or "is it a stupid idea, because the bijective mapping will never work reliably with serde".
The latter is still not clear to me - would it be possible ? I think serde guarantees you that the serializers will always be called in the order that the struct fields are defined - does this do it?

**Comment by dsxmachina** [comment] 2023-07-30 13:17
Nice - thanks for the clarification @frol .
I will give it a try next month - and can hopefully present some results.

**Comment by preston-evans98** [comment] 2023-08-22 17:33
Hey @dsxmachina (and FYI @frol), I looked at this in some depth a few months ago. Sadly, `borsh` is *not* compatible with `serde`'s data model right now. The root cause of the issue is that Serde doesn't have a `PartialOrd` bound on keys for its map types, but `borsh` requires maps to be sorted during serialization to ensure that serialization is canonical. AFAICT, there are two ways you can try to work around this issue:
1. Sort maps based on the *serialized* values of the keys. **This is safe, but its behavior will diverge from `borsh`'s in many cases.** (Integers are a good example; borsh uses little-endian, so the sorted order of serialized integers is completely different from numerical order). If all you care about is having a serde-compatible canonical serializer, you can take this approach though. If this is the route you take, you may want to look at the `bcs` library from Diem. 
2. Use [auto(de)ref specialization](https://lukaskalbertodt.github.io/2019/12/05/generalized-autoref-based-specialization.html) to try stay bitwise compatible with `borsh` *within the set of types that borsh already serializes* while also satisfying the compiler in the general case where keys are not comparable. (In the general case, you can either panic or try to fall back to comparing the serialized representation - both designs have tradeoffs, but that's a different discussion). Unfortunately, this design is extremely brittle. Autoref specialization only works with arguments to macros, not functions. And it doesn't work at all for nested structures. So, this approach can fail *silently* in a bunch of common cases, including if a user ever tries to serialize a nested map.

**Comment by frol** [comment] 2023-08-28 22:43
@preston-evans98 Thank you for diving into it and providing a detailed report! I will close this issue, but we may keep the conversation going and once it will become actionable, we may re-open it.

**Closed by frol** 2023-08-28 22:43 UTC

**Comment by dsxmachina** [comment] 2023-08-30 18:50
@preston-evans98 thanks for looking into this.

@frol Maybe its not a bad idea to mention this under the "Feature" section in one short sentence.
You already talk about serde there and say that you opted out for serde for two features - then you name the features.
